---
update: true
swapfile_path: /swapfile
swapfile_size: 8G

base_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - sudo
  - openssh
  - man-db
  - man-pages
  - git
  - wget
  - reflector

other_packages:
  - bash-completion
  - polkit
  - vi
  - nginx
  - anubis
  - podman
  - podman-compose
  - tailscale
  - rsync
  - hugo
  - bc

services_list:
  - sshd
  - nginx

dev_packages:
  - python
  - python-pip
