---
- name: Configure host.
  user: root
  hosts: vps

  vars_files:
    - config.yaml
    - vault.yaml

  tasks:
    - import_tasks: tasks/swap.yaml
    - import_tasks: tasks/update.yaml
      tags: update
    - import_tasks: tasks/base-packages.yaml
    - import_tasks: tasks/set-hostname.yaml
      tags: hostname
    - import_tasks: tasks/dev-packages.yaml
    - import_tasks: tasks/other-packages.yaml
      tags: packages

    - import_tasks: tasks/rob-user.yaml
      tags: rob
    - import_tasks: tasks/pods-user.yaml
      tags: pods
    - import_tasks: tasks/sudoers.yaml
      tags: sudoers

    - import_tasks: tasks/upgrade.yaml
      tags: update

    - import_tasks: tasks/nginx-setup.yaml
      tags: nginx-setup
    - import_tasks: tasks/other-services.yaml

    - import_tasks: tasks/podman-setup.yaml
      tags: podman-setup
    - import_tasks: tasks/ente.yaml
      tags: ente
    - import_tasks: tasks/searxng.yaml
      tags: searxng
    - import_tasks: tasks/piwigo.yaml
      tags: piwigo
    - import_tasks: tasks/immich.yaml
      tags: immich
