---
- name: Install sudo package
  community.general.pacman:
    name: sudo
    state: present

- name: Create sudo group
  ansible.builtin.group:
    name: sudo

- name: Add `sudo` group to sudoers
  community.general.sudoers:
    name: sudo-group
    group: sudo
    nopassword: false
    commands: ALL

- name: Increase faillock allowed retries
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: '.*deny \= 3'
    line: deny = 10
