---
- hosts: home_pis
  vars_files:
    - config/home-pis.yml
    - config/home-pis-vault.yml
  handlers:
    - import_tasks: handlers/main.yml

  roles:
    - role: swapfile
      become: true
      tags: swapfile

    - role: set-hostname
      become: true
      tags: set-hostname

    - role: sudoers
      become: true
      tags: sudoers

    - role: rob-user
      become: true
      tags: rob-user

    - role: arch-base
      become: true
      tags: arch-base

    - role: pkgbuilds
      become: true
      become_user: aur_builder
      tags: pkgbuilds
      when: pkgbuild_packages is defined

    - role: snapclient
      tags: snapclient

