---
- name: Copy music-assistant dir
  become: true
  become_user: pods
  ansible.builtin.copy:
    src: music-assistant/music-assistant
    dest: /home/pods

- name: Create music-assistant/data dir
  become: true
  become_user: pods
  ansible.builtin.file:
    path: /home/pods/music-assistant/data
    state: directory
    mode: 0755

- name: Copy music-assistant.service file
  become: true
  become_user: pods
  ansible.builtin.copy:
    src: music-assistant/music-assistant.service
    dest: /home/pods/.config/systemd/user/music-assistant.service
    mode: 0644

- name: Get pods user uid
  ansible.builtin.getent:
    database: passwd
    key: pods

- name: Store pods uid for later use
  ansible.builtin.set_fact:
    podsuid: "{{ getent_passwd['pods'][1] }}"

- name: Activate music-assistant systemd service
  become: true
  become_user: pods
  ansible.builtin.systemd_service:
    name: music-assistant.service
    state: started
    daemon-reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"

