---
- name: Import podsuid role
  import_role:
    name: podsuid

- name: Create piwigo compose folder
  ansible.builtin.file:
    path: /home/pods/piwigo
    state: directory

- name: Template piwigo compose.yaml file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: /home/pods/piwigo/compose.yaml
    mode: 0600
  notify: Restart piwigo systemd service

- name: Copy piwigo.service file
  ansible.builtin.copy:
    src: piwigo.service
    dest: /home/pods/.config/systemd/user/piwigo.service
    mode: 0644
  notify:
    - Reload pods user systemd config
    - Restart piwigo systemd service

- name: Enable piwigo systemd service
  ansible.builtin.systemd_service:
    name: piwigo.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"
