---
- name: Ping all machines
  ansible.builtin.ping:
  tags: ping

- name: Update all packages
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: present
  tags: update
  notify:
    - Restart host
