---
- name: Update package cache
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false

- name: Update all packages
  become: true
  community.general.pacman:
    upgrade: true
    state: present
  changed_when: false
  when: update | default(false) | bool
