---
# handlers file for podsuid
- name: Reload pods user systemd config
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"
