---
# handlers file for piwigo
- name: Reload systemd config
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"

- name: Restart piwigo systemd service
  ansible.builtin.systemd_service:
    name: piwigo.service
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"
