---
swapfile_path: /swapfile
swapfile_size: 8G

base_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - sudo
  - openssh
  - man-db
  - man-pages
  - git
  - wget

other_packages:
  - bash-completion
  - polkit
  - vi
  - nginx
  - podman
  - podman-compose
  - rsync
  - locate
  - mopidy

dev_packages:
  - python

aur_packages:
  - adduser
  - libtremor-git
  - mopidy-internetarchive
  - mopidy-iris
  - mopidy-local
  - mopidy-musicbox
  - mopidy-qsaver-git
  - python-cachetools
  - python-ratelimit
  - python-uritools
  - snapcast

pkgbuild_packages:
  - python-mopidy-mobile
  - python-mopidy-tidal-git
  - python-mopidy-tidallp-git
  - python-tidalapi-git
  
