---
swapfile_path: /swapfile
swapfile_size: 8G

host_packages:
  - mopidy
  - python-pyaes

host_aur_packages:
  - adduser
  - libtremor-git
  - mopidy-internetarchive
  - mopidy-iris
  - mopidy-local
  - mopidy-musicbox
  - mopidy-qsaver-git
  - python-cachetools
  - python-ratelimit
  - python-uritools
  - snapcast

host_pkgbuild_packages:
  - python-mopidy-mobile
  - python-mopidy-tidal-git
  - python-mopidy-tidallp-git
  - python-tidalapi-git
