---
swapfile_path: /swapfile
swapfile_size: 8G

base_packages:
  - base
  - base-devel
  - linux
  - linux-firmware
  - sudo
  - openssh
  - man-db
  - man-pages
  - git
  - wget

other_packages:
  - bash-completion
  - polkit
  - vim
  - rsync
  - locate

dev_packages:
  - python

aur_packages:
  - appstream-qt5
  - asdf-vm

pkgbuild_packages:
  - niri-session-manager-bin
