---
host_packages:
  - linux
  - linux-lts
  - tailscale

host_gui_packages:
  - mesa-demos
  - vulkan-radeon

host_aur_packages:
  - paru
  - firefox-nightly-bin

niri_configs:
  - mako
  - niri
  - niri-session-manager
  - niriswitcher
  - waybar
