---
host_packages:
   - zsh

host_aur_packages:
  - firefox-nightly-bin

host_pkgbuild_packages:
  - zohomeeting
  - ardour
  - katana-proxy-git
  - midiminder
  - nilsk1v
  - tuxguitar-bin
  - zl-compressor-bin
  - zl-equalizer-bin
  - zl-splitter-bin
  - zl-warm-bin

host_gui_packages:
  - xdotool
  - plasma-x11-session
  - mesa-demos

niri_configs:
  - mako
  - niri
  - niri-session-manager
  - niriswitcher
  - waybar
