---
- name: Create piwigo compose folder
  become: true
  become_user: pods
  ansible.builtin.file:
    path: /home/pods/piwigo
    state: directory

- name: Template piwigo compose.yaml file
  become: true
  become_user: pods
  ansible.builtin.template:
    src: piwigo/compose.yaml.j2
    dest: /home/pods/piwigo/compose.yaml
    mode: 0600

- name: Copy piwigo.service file
  become: true
  become_user: pods
  ansible.builtin.copy:
    src: piwigo/piwigo.service
    dest: /home/pods/.config/systemd/user/piwigo.service
    mode: 0644

- name: Get pods user uid
  ansible.builtin.getent:
    database: passwd
    key: pods

- name: Store pods uid for later use
  ansible.builtin.set_fact:
    podsuid: "{{ getent_passwd['pods'][1] }}"

- name: Activate piwigo systemd service
  become: true
  become_user: pods
  ansible.builtin.systemd_service:
    name: piwigo.service
    state: started
    daemon-reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"

