---
- name: Check for /home/aur_builder/src
  ansible.builtin.file:
    path: /home/aur_builder/src
    state: directory

- name: Checkout PKGBUILDs git repo
  ansible.builtin.git:
    repo: https://github.com/rafrombrc/PKGBUILDs
    dest: /home/aur_builder/src/PKGBUILDs

- name: Install PKGBUILD packages
  kewlfft.aur.aur:
    use: makepkg
    local_pkgbuild: /home/aur_builder/src/PKGBUILDs/{{ item }}
    name: "{{ item }}"
  loop: "{{ pkgbuild_packages }}"
  when: pkgbuild_packages is defined
