---
- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  tags: packages

- name: Infer timezone from /etc/localtime
  ansible.builtin.stat:
    path: /etc/localtime
  register: localtime_stat
  tags: timezone

- name: Set /etc/timezone
  ansible.builtin.lineinfile:
    path: /etc/timezone
    regexp: '.*'
    line: "{{ localtime_stat.stat.lnk_source | dirname | basename }}/{{ localtime_stat.stat.lnk_source | basename }}"
    create: true
  tags: timezone

- import_playbook: aur_builder.yml

- name: Install paru-bin
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: paru-bin
    use: makepkg
    state: present

- name: Install host packages
  community.general.pacman:
    name: "{{ host_packages }}"
    state: present
  when: host_packages is defined
  tags: packages

- name: Install host AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name: "{{ host_aur_packages }}"
    state: present
  when: host_aur_packages is defined
  tags: aur_packages

- name: Install host PKGBUILD packages
  kewlfft.aur.aur:
    use: makepkg
    local_pkgbuild: /home/aur_builder/src/PKGBUILDs/{{ item }}
    name: "{{ item }}"
  loop: "{{ host_pkgbuild_packages }}"
  when: host_pkgbuild_packages is defined
  tags: pkgbuild_packages

- name: Install dev packages
  community.general.pacman:
    name: "{{ dev_packages }}"
    state: present
  when: dev_packages is defined
  tags: packages

- name: Install host dev packages
  community.general.pacman:
    name: "{{ host_dev_packages }}"
    state: present
  when: host_dev_packages is defined
  tags: packages

- name: Install dev AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name: "{{ dev_aur_packages }}"
    state: present
  when: dev_aur_packages is defined
  tags: aur_packages

- name: Install dev PKGBUILD packages
  kewlfft.aur.aur:
    use: makepkg
    local_pkgbuild: /home/aur_builder/src/PKGBUILDs/{{ item }}
    name: "{{ item }}"
  loop: "{{ dev_pkgbuild_packages }}"
  when: dev_pkgbuild_packages is defined
  tags: pkgbuild_packages

- name: Install gui packages
  community.general.pacman:
    name: "{{ gui_packages }}"
    state: present
  when: gui_packages is defined
  tags: packages

- name: Install host gui packages
  community.general.pacman:
    name: "{{ host_gui_packages }}"
    state: present
  when: host_gui_packages is defined
  tags: packages

- name: Install gui AUR packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: paru
    name: "{{ gui_aur_packages }}"
    state: present
  when: gui_aur_packages is defined
  tags: aur_packages

- name: Install gui PKGBUILD packages
  kewlfft.aur.aur:
    use: makepkg
    local_pkgbuild: /home/aur_builder/src/PKGBUILDs/{{ item }}
    name: "{{ item }}"
  loop: "{{ gui_pkgbuild_packages }}"
  when: gui_pkgbuild_packages is defined
  tags: pkgbuild_packages
