---
- name: Install base packages
  become: true
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present

- name: Install other packages
  become: true
  community.general.pacman:
    name: "{{ other_packages }}"
    state: present

- name: Install dev packages
  become: true
  community.general.pacman:
    name: "{{ dev_packages }}"
    state: present
