---
- name: Import podsuid role
  import_role:
    name: podsuid

- name: Copy music-assistant dir
  ansible.builtin.copy:
    src: music-assistant
    dest: /home/pods

- name: Create music-assistant/data dir
  ansible.builtin.file:
    path: /home/pods/music-assistant/data
    state: directory
    mode: 0755

- name: Copy music-assistant.service file
  ansible.builtin.copy:
    src: music-assistant.service
    dest: /home/pods/.config/systemd/user/music-assistant.service
    mode: 0644

- name: Enable music-assistant systemd service
  ansible.builtin.systemd_service:
    name: music-assistant.service
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podsuid }}"
