---
# handlers file for anubis
- name: Restart anubis service
  become: true
  ansible.builtin.systemd_service:
    name: anubis@nginx.service
    state: restarted

- name: Restart nginx service
  become: true
  ansible.builtin.systemd_service:
    name: nginx.service
    state: restarted
